language: rust
rust:
  - 1.42.0
os: linux
dist: bionic
services:
  - postgresql
cache: cargo
env:
  global:
    - DATABASE_URL="postgres://test_framework_user:test@localhost:5432/test_framework_db"
    - PGPORT=5432
before_script:
  - sudo -u postgres psql -c 'create database test_framework_db;'
  - sudo -u postgres psql -c "create user test_framework_user with password 'test' superuser;"
  - sudo -u postgres psql -c 'create extension if not exists "uuid-ossp";' test_framework_db
