language: rust
rust:
  - 1.42.0
os: linux
dist: bionic
services:
 - postgresql
addons:
  postgresql: "12"
  apt:
    packages:
     - postgresql-12
     - postgresql-client-12
cache: cargo
env:
  global:
   - DB_USER="test_framework_user"
   - DB_PASS="test"
   - DB_NAME="test_framework_db"
   - DATABASE_URL="postgres://${DB_USER}:${DB_PASS}@localhost:5432/${DB_NAME}"
   - PGPORT=5432
before_script: 
 - sudo -u postgres psql -c 'create database ${DB_NAME};'
 - sudo -u postgres psql -c "create user ${DB_USER} with password '${DB_PASS}'"
