language: rust
rust:
  - 1.42.0
os: linux
dist: bionic
services:
 - postgresql
addons:
  postgresql: "12"
  apt:
    packages:
     - postgresql-12
     - postgresql-client-12
cache: cargo
env:
  global:
   - DATABASE_URL="postgres://postgres:@localhost:5432/test_framework_db"
   - PG_PORT=5432
before_script: 
 - psql -c 'create database test_framework_db;' -U postgres
