language: rust
rust:
  - 1.42.0
os: linux
dist: bionic
services:
 - postgresql
cache: cargo
env:
  global:
   - DATABASE_URL="postgres://postgres:@localhost:5432/test_framework_db"
before_script: 
 - psql -c 'create database test_framework_db;' -U postgres
