language: rust
rust:
  - 1.42.0
os: linux
dist: bionic
services:
 - docker
cache: cargo
env:
  global:
   - DB=test_framework_db
   - USER=test_framework_user
   - PASS=test
   - DATABASE_URL="postgres://${USER}:${PASS}@localhost:5432/${DB}"
before_script: 
 - docker-compose -f scripts/docker/test/docker-compose.yml .
