[package]
name = "carrot"
version = "0.1.0"
authors = ["Kevin Lydon <klydon@broadinstitute.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Web framework
actix-web = "2.0.0"
actix-rt = "1.0.0"
actix-service = "1.0.5"
# Environment variables
dotenv = "0.15.0"
# Logging
env_logger = "0.7.1"
log = "0.4.8"
# DB connection and pooling
postgres = { version = "0.17.1", features = ["with-uuid-0_8"] }
r2d2 = "0.8.8"
r2d2_postgres = "0.16.0"
# Serializing/Deserializing data
serde = "1.0.104"
serde_json = "1.0.48"
uuid = { version = "0.8", features = ["serde", "v4"] }


